name: Publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI

on:
  push:
    branches:
      - master

jobs:
  build-n-publish:
    name: Build and publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-20.04

    environment:
      name: pypi
      url: https://pypi.org/p/chombopy
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install locally
        run: |
          python3 -m pip install build -r requirements.txt -r requirements_test.txt --user

      - name: Run unit tests before deployment
        run: |
          sudo apt-get install libhdf5-serial-dev
          pip install -r requirements.txt
          py.test

      - name: Build binary
        run:
          python3 -m build

      # Publish to PyPI (not test) if tags are included in the push
      # Always try and publish to PyPI. Will succeed if version is new
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Get version
        id: version
        run: |
          echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

      # Tag if succesful
      - name: Tag release
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/{{steps.version.outputs.version}}",
              sha: context.sha
            })
